[messages for room 43



%message	1
"This is the main hallway of the Horned King's castle."

%message	2
"The closet is empty."

%message	3
"Ah ha! You've found your knapsack and all your missing belongings."

%message	4
"Oh, no! The gwythaint got you! He holds you until a
 henchman appears and marches you off to the dungeon."

%message  5
"Oh, no! You've allowed the Horned King to capture your Magic Sword."

%message	6
"The gwythaint appears to be hungry for Assistant Pig-Keeper!"

%message	7
"By allowing the pig and yourself to be captured, the Horned
 King has won!"

%message	8
"Reaching into the closet, you reclaim your possessions."

%message	9
"There is a closed door here."

%message	10
"Carefully watching over your shoulder, you open the closet door."
